base:
  orientation: 0.0 0.0 0.0
  position: 0.0 0.0 0.0
  size: 1.0 1.0 0.1
  color: 1 1 1 1
links: 
- orientation: 0.0 0.0 0.0
  position: 0.0 0.0 0.0
  size: 0.5 0.25 1.0
  color: 1 1 1 1
- orientation: 0.0 0.0 0.0
  position: 0.0 0.0 0.0
  size: 0.0 0.0 0.0
  color: 1 1 1 1
- orientation: 0.0 0.0 0.0
  position: 0.0 0.0 0.0
  size: 1.25 0.50 0.25
  color: 1 1 1 1
